### PR TITLE
fix depwarns

### PR DESCRIPTION
**Pull request by jw3126**

### CODE REVIEW

**Comment by tpapp** [comment]
Can you please complete and merge this? I am using `@argcheck` a lot, but warnings on `v0.7` are really affecting my benchmarks.

**Comment by jw3126** [comment]
@tpapp can you check if this fixes the depwarns for you? If so I will tag a new release.

**Comment by tpapp** [comment]
@jw3126: this fixed everything, no `ArgCheck` code shows up in profiling now, thank you so much for the quick work!

**Comment by jw3126** [comment]
tagged https://github.com/JuliaLang/METADATA.jl/pull/15269

**Pull request merged**
